plugins {
    id 'fabric-loom' version '1.3.+'

    id "io.github.juuxel.loom-vineflower" version "1.+" // Vineflower, a better decompiler
    id "io.github.p03w.machete" version "1.1.4" // automatic jar compressing on build

    id 'maven-publish'
}

sourceCompatibility = JavaVersion.VERSION_17
targetCompatibility = JavaVersion.VERSION_17

archivesBaseName = project.archives_base_name
group = project.maven_group

String buildNumber = System.getenv("GITHUB_RUN_NUMBER")
version = "${mod_version}+${minecraft_version}" + (buildNumber != null ? "-${buildNumber}" : "")

repositories {

    mavenLocal() //local maven for Magna JIJ
    mavenCentral()
    maven { url 'https://jitpack.io' }

    maven { url = "https://maven.parchmentmc.org" } // Parchment mappings
    maven { url = "https://maven.quiltmc.org/repository/release" } // Quilt Mappings

    maven { url = "https://modmaven.dev" } // JEI
    maven { url = "https://maven.shedaniel.me/" } // Cloth Config, REI
    maven { url = "https://api.modrinth.com/maven" } // LazyDFU, Additional Entity Attributes
    maven { url = "https://maven.terraformersmc.com/" } // Mod Menu, Trinkets, EMI
    maven { url = "https://maven.ladysnake.org/releases" } // CCA for Trinkets
    maven { // Reach Entity Attributes
        url = "https://maven.jamieswhiteshirt.com/libs-release"
        content { includeGroup("com.jamieswhiteshirt") }
    }
    maven { url = "https://mvn.devos.one/snapshots/" } // Porting-Lib
}

dependencies {
    // Setup
    minecraft("com.mojang:minecraft:${minecraft_version}")
    mappings(loom.layered {
        it.mappings("org.quiltmc:quilt-mappings:${minecraft_version}+build.${quilt_mappings_version}:intermediary-v2")
        it.parchment("org.parchmentmc.data:parchment-${minecraft_version}:${parchment_version}@zip")
        it.officialMojangMappings { nameSyntheticMembers = false }
    })
    modImplementation("net.fabricmc:fabric-loader:${fabric_loader_version}")

    // dependencies
    modImplementation("net.fabricmc.fabric-api:fabric-api:${fabric_api_version}")
    include modImplementation("com.jamieswhiteshirt:reach-entity-attributes:$reach_entity_attributes_version")
    include modImplementation("maven.modrinth:AdditionalEntityAttributes:$additional_entity_attributes_version")
    include modImplementation("com.github.Draylar.omega-config:omega-config-base:$omega_config_version")
    include modImplementation ("dev.draylar:magna:${project.magna_version}") {
        exclude group: "net.fabricmc"
        exclude group: "com.jamieswhiteshirt"
        exclude group: "me.shedaniel.cloth"
    }

    // Porting Lib Modules
    for (String module in port_lib_modules.split(",")) {
        include modImplementation("io.github.fabricators_of_create.Porting-Lib:$module:$port_lib_version")
    }

    // compatibility
    modCompileOnly("com.terraformersmc:modmenu:$modmenu_version")
    modCompileOnly("dev.emi:trinkets:$trinkets_version")
    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-base:$cca_version")
    modCompileOnly("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:$cca_version")

    // Development QOL
    modLocalRuntime("maven.modrinth:lazydfu:${lazydfu_version}")
    modLocalRuntime("com.terraformersmc:modmenu:${modmenu_version}")
    modLocalRuntime("dev.emi:trinkets:$trinkets_version") { transitive = false }
    modLocalRuntime("dev.onyxstudios.cardinal-components-api:cardinal-components-base:$cca_version")
    modLocalRuntime("dev.onyxstudios.cardinal-components-api:cardinal-components-entity:$cca_version")
    // https://github.com/PlanetTeamSpeakk/DevLogin
    modImplementation("com.ptsmods:devlogin:3.3.2") //dev login

    recipeViewers(dependencies)
}

// setup the three recipe viewer mods
def recipeViewers(DependencyHandler deps) {
    // EMI
    deps.modCompileOnly("dev.emi:emi-fabric:$emi_version:api") { transitive = false }
    // JEI
    deps.modCompileOnly("mezz.jei:jei-$minecraft_version-fabric:$jei_version") { transitive = false }
    // REI
    deps.modCompileOnly("me.shedaniel:RoughlyEnoughItems-api-fabric:$rei_version")
    deps.modCompileOnly("me.shedaniel:RoughlyEnoughItems-default-plugin-fabric:$rei_version")

    switch (recipe_viewer.toLowerCase(Locale.ROOT)) {
        case "jei": deps.modLocalRuntime("mezz.jei:jei-$minecraft_version-fabric:$jei_version"); break
        case "rei": deps.modLocalRuntime("me.shedaniel:RoughlyEnoughItems-fabric:$rei_version"); break
        case "emi": deps.modLocalRuntime("dev.emi:emi-fabric:$emi_version"); break
        case "disabled": break
        default: println("Unknown recipe viewer specified: $recipe_viewer. Must be JEI, REI, EMI, or disabled.")
    }
}

processResources {
    Map<String, Object> properties = new HashMap<>()
    properties.put("version", version)
    properties.put("fabric_loader_version", fabric_loader_version)
    properties.put("fabric_api_version", fabric_api_version)
    properties.put("minecraft_version", minecraft_version)

    properties.forEach((k, v) -> inputs.property(k, v))

    filesMatching("fabric.mod.json") {
        expand properties
    }
}

machete {
    // disable machete locally for faster builds
    enabled = buildNumber != null
}

tasks.withType(JavaCompile).configureEach {
    // ensure that the encoding is set to UTF-8, no matter what the system default is
    // this fixes some edge cases with special characters not displaying correctly
    // see http://yodaconditions.net/blog/fix-for-java-file-encoding-problems-with-gradle.html
    // If Javadoc is generated, this must be specified in that task too.
    it.options.encoding = "UTF-8"
    it.options.release = Integer.parseInt(sourceCompatibility)
}

java {
    if (JavaVersion.current() < targetCompatibility) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetCompatibility)
    }
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()
}

jar {
    from("LICENSE") {
        rename { "${it}_${archivesBaseName}"}
    }
}

loom {
    runs {
        //
        // This adds a new gradle task that runs the datagen API: "gradlew runDatagenClient"
        //
        datagenClient {
            inherit client
            name "Data Generation"
            vmArg "-Dfabric-api.datagen"
            vmArg "-Dfabric-api.datagen.output-dir=${file("src/main/generated")}"
            vmArg "-Dfabric-api.datagen.modid=${modid}"

            runDir "build/datagen"
        }
    }
}

//
// Adds the generated files into the jar you distribute to players.
//
sourceSets {
    main {
        resources {
            srcDirs += [
                    'src/main/generated'
            ]
        }
    }
}

// configure the maven publication
publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
