# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# ====Mod Properties====
modid=alloygery
mod_version = 3.0-DEV
maven_group = amorphia
archives_base_name = Alloygery

# ====Minecraft Properties====
minecraft_version=1.20.1

# ====Fabric Properties====
# https://fabricmc.net/develop
fabric_loader_version=0.16.11
fabric_api_version=0.92.5+1.20.1

# ====Mappings====
# https://parchmentmc.org/docs/getting-started
parchment_version=2023.09.03

# ====Dependencies====
# https://maven.jamieswhiteshirt.com/libs-release/com/jamieswhiteshirt/reach-entity-attributes/
reach_entity_attributes_version = 2.4.0
# https://modrinth.com/mod/additionalentityattributes/versions
additional_entity_attributes_version = 1.7.6+1.20.1
# https://modrinth.com/mod/ranged-weapon-api/versions
ranged_weapon_api_version = 1.1.4+1.20.1
# https://modrinth.com/mod/shield-api/versions
shield_api_version = 1.0.1+1.20.1
# https://github.com/Draylar/magna
magna_version = 1.10.1+1.20.1
# for magna - https://github.com/Draylar/omega-config
omega_config_version = 1.0.8-1.17
# porting lib - https://modrinth.com/mod/porting_lib/versions
port_lib_version = 2.3.8+1.20.1
port_lib_modules = attributes,data,tool_actions,loot

# ====Development QOL====
# set to jei, rei, emi, or disabled to have none of them.
recipe_viewer = emi
# JEI - https://www.curseforge.com/minecraft/mc-mods/jei/files/all
jei_version = 15.20.0.106
# REI - https://modrinth.com/mod/rei/versions
rei_version = 12.1.785
# EMI - https://modrinth.com/mod/emi/versions
emi_version = 1.1.21+1.20.1

# ====Compatibility===
# Mod Menu - https://modrinth.com/mod/modmenu/versions
modmenu_version = 7.2.2
# https://github.com/emilyploszaj/trinkets/releases/
trinkets_version = 3.7.1
# for Trinkets - https://modrinth.com/mod/cardinal-components-api/versions
cca_version = 5.2.3
